package httpserver.handlers;

public enum HandlerType {

    BASIC_AUTH_HANDLER,
    COOKIE_HANDLER,
    DELETE_HANDLER,
    DIRECTORY_LISTING_HANDLER,
    FORM_HANDLER,
    GET_HANDLER,
    HEAD_HANDLER,
    INTERNAL_ERROR_HANDLER,
    INVALID_REQUEST_HANDLER,
    NOT_ALLOWED_HANDLER,
    OPTION_HANDLER,
    PARAMETERS_HANDLER,
    PATCH_HANDLER,
    POST_HANDLER,
    REDIRECT_HANDLER,
    PUT_HANDLER,
    TEAPOT_HANDLER;
}
